# Generated by Django 4.2.5 on 2023-11-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.brand', verbose_name='Бренд машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавлении машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество свободных машин'),
        ),
    ]
