# Generated by Django 4.2.5 on 2023-11-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_surcharges',
            field=models.IntegerField(default=3, verbose_name='Топливные сборы'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_day',
            field=models.IntegerField(default=300, verbose_name='Цена машины за день'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_hour',
            field=models.IntegerField(default=30, verbose_name='Цена машины за час'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_month',
            field=models.IntegerField(default=4500, verbose_name='Цена машины за месяц'),
        ),
    ]
