# Generated by Django 4.2.5 on 2023-11-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_description',
            field=models.TextField(default='содержание', verbose_name='Полное содержание статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='описание', verbose_name='Краткое содержание статьи'),
        ),
    ]
